# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3761888b2e2748dd2433e73cdea53f7d0c865000e312ba0befce0eadb54018489c187dbec470959623225ba86ebacd74263bf4712bd23078518178534a82e244

test:
  secret_key_base: 696378cd3ab3901c74b3614157986ed26f5e4139bb6e0d76110b166a4299f1699ba4d9c3195eae3d5c2bc09a4455500ce9dea28dcc1a4bafc3508ef289d6a26c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
